name: Test WIF Connection

on:
  workflow_dispatch: # Esto permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  test_connection:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Crucial para OIDC

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Test: List Buckets'
      run: |
        gcloud storage ls